variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
    SolutionBaseName: 'Dfc.Api.DiscoverSkillsAndCareers'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

trigger:
  - v1-*

pr: 
  - v1-dev
  - v1-master

- stage: Build
  displayName: Build, Test and Analyze
  jobs:

  #Build and test resources
  - job: BuildArmTemplates
    displayName: Test ARM templates
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)

  #Build and test application
  - job: BuildTestAndAnalyze
    displayName: Build test and analyze DotNet Core funtion app
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.101'
        PublishWebApp: true
        TestSuffix: UnitTests